apiVersion: v1
kind: Service
metadata:
  annotations:
    cloud.google.com/neg: '{"ingress":true}'
  creationTimestamp: "2022-10-03T19:54:31Z"
  finalizers:
  - service.kubernetes.io/load-balancer-cleanup
  labels:
    app: petclinic-app
  name: petclinic-appv1
  namespace: default
  resourceVersion: "13256"
  uid: 373b827d-7468-4b16-820a-dadd0baf3405
spec:
  allocateLoadBalancerNodePorts: true
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 32150
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: petclinic-app1
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - ip: 35.232.6.243
